# Generated by Django 4.1.4 on 2023-01-08 20:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=50)),
                ('account_value', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountTransactions',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('transaction_value', models.FloatField()),
                ('transaction_description', models.CharField(blank=True, max_length=100, null=True)),
                ('current_account_value', models.FloatField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_management.account')),
            ],
            options={
                'verbose_name': 'Account Transactions',
            },
        ),
    ]
