# Generated by Django 4.1.4 on 2023-01-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accounttransactions',
            options={'verbose_name_plural': 'Account Transactions'},
        ),
    ]
