# Generated by Django 4.1.4 on 2022-12-31 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_country', models.CharField(max_length=50)),
                ('home_office', models.CharField(max_length=200)),
            ],
        ),
    ]
