# Generated by Django 4.1.4 on 2022-12-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_company_data', '0002_alter_companycore_options_companycore_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycore',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
