# Generated by Django 4.1.4 on 2023-01-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_company_data', '0006_rename_price_pricedata_close_pricedata_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedata',
            name='market_cap',
        ),
    ]
