# Generated by Django 4.1.4 on 2023-01-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_company_data', '0007_remove_pricedata_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='price_ticker_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
