# Generated by Django 4.1.4 on 2023-01-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_company_data', '0009_alter_pricedata_price_ticker_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricedata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Company Price Timeseries'},
        ),
        migrations.AddField(
            model_name='pricedata',
            name='daily_pct_change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
